/**
 * Add Station Page
 * Dedicated page for adding new fuel stations
 */

import { useState } from 'react';
import { Info } from 'lucide-react';
import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip';
import { useMutation } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { apiClient } from '@/lib/api-client';
import { queryKeys } from '@/hooks/api';
import { useQueryClient } from '@tanstack/react-query';
import {
  ArrowLeft,
  Building2,
  Plus
} from 'lucide-react';

interface StationFormData {
  name: string;
  code: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  email: string;
  gstNumber: string;
}

const initialFormData: StationFormData = {
  name: '',
  code: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  phone: '',
  email: '',
  gstNumber: ''
};

const StationFormContent = ({ formData, onChange, formErrors = {} }: {
  formData: StationFormData;
  onChange: (data: StationFormData) => void;
  formErrors?: Record<string, string>;
}) => (
  <div className="grid gap-6">
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Label htmlFor="name" className="text-sm font-medium">Station Name *</Label>
          <Tooltip>
            <TooltipTrigger asChild>
              <Info className="w-4 h-4 text-muted-foreground cursor-pointer" />
            </TooltipTrigger>
            <TooltipContent>
              Required. Min 2 characters.
            </TooltipContent>
          </Tooltip>
        </div>
        <Input
          id="name"
          value={formData.name}
          onChange={(e) => onChange({ ...formData, name: e.target.value })}
          placeholder="Main Station"
          autoComplete="off"
          className={formErrors.name ? 'border-red-500' : ''}
        />
        {formErrors.name && <p className="text-xs text-red-500 mt-1">{formErrors.name}</p>}
      </div>
      <div className="space-y-2">
        <Label htmlFor="code" className="text-sm font-medium">Station Code</Label>
        <Input
          id="code"
          value={formData.code}
          readOnly
          disabled
          placeholder="Auto-generated by system"
          className="bg-muted cursor-not-allowed"
        />
        <p className="text-xs text-muted-foreground">Auto-generated by the system</p>
      </div>
    </div>

    <div className="space-y-2">
      <Label htmlFor="address" className="text-sm font-medium">Address</Label>
      <Input
        id="address"
        value={formData.address}
        onChange={(e) => onChange({ ...formData, address: e.target.value })}
        placeholder="Street address"
        autoComplete="off"
      />
    </div>

    <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
      <div className="space-y-2">
        <Label htmlFor="city" className="text-sm font-medium">City</Label>
        <Input
          id="city"
          value={formData.city}
          onChange={(e) => onChange({ ...formData, city: e.target.value })}
          placeholder="Mumbai"
          autoComplete="off"
        />
      </div>
      <div className="space-y-2">
        <Label htmlFor="state" className="text-sm font-medium">State</Label>
        <Input
          id="state"
          value={formData.state}
          onChange={(e) => onChange({ ...formData, state: e.target.value })}
          placeholder="Maharashtra"
          autoComplete="off"
        />
      </div>
      <div className="space-y-2">
        <Label htmlFor="pincode" className="text-sm font-medium">Pincode</Label>
        <Input
          id="pincode"
          value={formData.pincode}
          onChange={(e) => onChange({ ...formData, pincode: e.target.value })}
          placeholder="400001"
          autoComplete="off"
          className={formErrors.pincode ? 'border-red-500' : ''}
        />
        {formErrors.pincode && <p className="text-xs text-red-500 mt-1">{formErrors.pincode}</p>}
      </div>
    </div>

    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <div className="space-y-2">
        <Label htmlFor="phone" className="text-sm font-medium">Phone</Label>
        <Input
          id="phone"
          value={formData.phone}
          onChange={(e) => onChange({ ...formData, phone: e.target.value })}
          placeholder="+91-9876543210"
          autoComplete="off"
          className={formErrors.phone ? 'border-red-500' : ''}
        />
        {formErrors.phone && <p className="text-xs text-red-500 mt-1">{formErrors.phone}</p>}
      </div>
      <div className="space-y-2">
        <Label htmlFor="email" className="text-sm font-medium">Email</Label>
        <Input
          id="email"
          type="email"
          value={formData.email}
          onChange={(e) => onChange({ ...formData, email: e.target.value })}
          placeholder="station@example.com"
          autoComplete="off"
          className={formErrors.email ? 'border-red-500' : ''}
        />
        {formErrors.email && <p className="text-xs text-red-500 mt-1">{formErrors.email}</p>}
      </div>
    </div>

    <div className="space-y-2">
      <Label htmlFor="gstNumber" className="text-sm font-medium">GST Number</Label>
      <Input
        id="gstNumber"
        value={formData.gstNumber}
        onChange={(e) => onChange({ ...formData, gstNumber: e.target.value })}
        placeholder="27AABCU9603R1ZX"
        autoComplete="off"
        className={formErrors.gstNumber ? 'border-red-500' : ''}
      />
      {formErrors.gstNumber && <p className="text-xs text-red-500 mt-1">{formErrors.gstNumber}</p>}
    </div>
  </div>
);

export default function AddStation() {
  const [formData, setFormData] = useState<StationFormData>(initialFormData);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});

  const { toast } = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  // Create station mutation
  const createMutation = useMutation({
    mutationFn: async (data: StationFormData) => {
      // Don't send code - backend generates it
      const { code, ...payload } = data;
      const response = await apiClient.post('/stations', payload);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station created successfully'
      });
      navigate('/owner/stations');
    },
    onError: (error: unknown) => {
      let message = 'Failed to create station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  // Validation logic
  const validateForm = (data: StationFormData) => {
    const errors: Record<string, string> = {};
    if (!data.name.trim()) {
      errors.name = 'Station name is required';
    } else if (data.name.trim().length < 2) {
      errors.name = 'Station name must be at least 2 characters';
    }
    if (!data.phone.trim()) {
      errors.phone = 'Phone number is required';
    } else if (!/^\d{10}$/.test(data.phone.trim())) {
      errors.phone = 'Enter a valid 10-digit phone number';
    }
    if (data.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim())) {
      errors.email = 'Enter a valid email address';
    }
    if (data.pincode && !/^\d{6}$/.test(data.pincode.trim())) {
      errors.pincode = 'Pincode must be 6 digits';
    }
    if (data.gstNumber) {
      const gst = data.gstNumber.trim().toUpperCase();
      const gstRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
      if (!gstRegex.test(gst)) {
        errors.gstNumber = 'Invalid GST number format';
      }
    }
    return errors;
  };

  const isFormValid = Object.keys(validateForm(formData)).length === 0;

  const handleCreate = () => {
    const errors = validateForm(formData);
    setFormErrors(errors);
    if (Object.keys(errors).length > 0) {
      toast({
        title: 'Validation Error',
        description: Object.values(errors).join('; '),
        variant: 'destructive',
      });
      return;
    }
    createMutation.mutate(formData);
  };

  return (
    <div className="container mx-auto p-4 md:p-6 max-w-4xl">
      {/* Header */}
      <div className="flex items-center gap-4 mb-6">
        <Button
          variant="outline"
          size="sm"
          onClick={() => navigate('/owner/stations')}
          className="flex items-center gap-2"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Stations
        </Button>
        <div>
          <h1 className="text-2xl md:text-3xl font-bold tracking-tight flex items-center gap-3">
            <div className="p-2 rounded-lg bg-primary/10">
              <Plus className="w-6 h-6 text-primary" />
            </div>
            Add New Station
          </h1>
          <p className="text-muted-foreground text-sm md:text-base mt-1">
            Create a new fuel station
          </p>
        </div>
      </div>

      {/* Form Card */}
      <Card className="shadow-lg">
        <CardHeader className="bg-gradient-to-r from-primary/5 to-transparent border-b">
          <CardTitle className="flex items-center gap-2">
            <Building2 className="w-5 h-5 text-primary" />
            Station Information
          </CardTitle>
        </CardHeader>
        <CardContent className="p-6 md:p-8">
          <StationFormContent
            formData={formData}
            onChange={setFormData}
            formErrors={formErrors}
          />

          {/* Action Buttons */}
          <div className="flex flex-col sm:flex-row justify-end gap-4 mt-8 pt-6 border-t">
            <Button
              variant="outline"
              onClick={() => navigate('/owner/stations')}
              className="w-full sm:w-auto"
            >
              Cancel
            </Button>
            <Button
              onClick={handleCreate}
              disabled={createMutation.isPending || !isFormValid}
              className="w-full sm:w-auto"
            >
              {createMutation.isPending ? 'Creating...' : 'Create Station'}
            </Button>
          </div>

          {/* Show all validation errors below the button if form is invalid */}
          {!isFormValid && (
            <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
              <h4 className="text-sm font-medium text-red-800 mb-2">Please fix the following errors:</h4>
              <ul className="text-sm text-red-700 space-y-1 list-disc list-inside">
                {Object.values(validateForm(formData)).map((err, idx) => (
                  <li key={idx}>{err}</li>
                ))}
              </ul>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}