/**
 * Owner Stations Management
 * Complete CRUD for managing stations
 */

import { useState } from 'react';
import { Info } from 'lucide-react';
import { Tooltip, TooltipTrigger, TooltipContent } from '@/components/ui/tooltip';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { apiClient } from '@/lib/api-client';
import { useStations, queryKeys } from '@/hooks/api';
import { safeToFixed } from '@/lib/format-utils';
import { Station } from '@/types/api';
import { 
  Plus, 
  Building2, 
  Edit, 
  Trash2,
  ArrowRight,
  MapPin,
  Phone,
  Fuel,
  TrendingUp,
  IndianRupee,
  ChevronDown,
  ChevronUp
} from 'lucide-react';

interface StationFormData {
  name: string;
  code: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  email: string;
  gstNumber: string;
}

const initialFormData: StationFormData = {
  name: '',
  code: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  phone: '',
  email: '',
  gstNumber: ''
};

// Separate component to prevent re-renders
interface StationFormProps {
  formData: StationFormData;
  onChange: (data: StationFormData) => void;
}

const StationFormContent = ({ formData, onChange, formErrors = {} }: StationFormProps & { formErrors?: Record<string, string> }) => (
  <div className="grid gap-4">
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <div className="flex items-center gap-1">
          <Label htmlFor="name">Station Name *</Label>
          <Tooltip>
            <TooltipTrigger asChild>
              <Info className="w-4 h-4 text-muted-foreground cursor-pointer" />
            </TooltipTrigger>
            <TooltipContent>
              Required. Min 2 characters.
            </TooltipContent>
          </Tooltip>
        </div>
        <Input
          id="name"
          value={formData.name}
          onChange={(e) => onChange({ ...formData, name: e.target.value })}
          placeholder="Main Station"
          autoComplete="off"
          className={formErrors.name ? 'border-red-500' : ''}
        />
        {formErrors.name && <p className="text-xs text-red-500 mt-1">{formErrors.name}</p>}
      </div>
      <div>
        <Label htmlFor="code">Station Code</Label>
        <Input
          id="code"
          value={formData.code}
          readOnly
          disabled
          placeholder="Auto-generated by system"
          className="bg-muted cursor-not-allowed"
        />
        <p className="text-xs text-muted-foreground mt-1">Auto-generated by the system</p>
      </div>
    </div>

    <div>
      <Label htmlFor="address">Address</Label>
      <Input
        id="address"
        value={formData.address}
        onChange={(e) => onChange({ ...formData, address: e.target.value })}
        placeholder="Street address"
        autoComplete="off"
      />
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <div>
        <Label htmlFor="city">City</Label>
        <Input
          id="city"
          value={formData.city}
          onChange={(e) => onChange({ ...formData, city: e.target.value })}
          placeholder="Mumbai"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="state">State</Label>
        <Input
          id="state"
          value={formData.state}
          onChange={(e) => onChange({ ...formData, state: e.target.value })}
          placeholder="Maharashtra"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="pincode">Pincode</Label>
        <Input
          id="pincode"
          value={formData.pincode}
          onChange={(e) => onChange({ ...formData, pincode: e.target.value })}
          placeholder="400001"
          autoComplete="off"
          className={formErrors.pincode ? 'border-red-500' : ''}
        />
        {formErrors.pincode && <p className="text-xs text-red-500 mt-1">{formErrors.pincode}</p>}
      </div>
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <Label htmlFor="phone">Phone</Label>
        <Input
          id="phone"
          value={formData.phone}
          onChange={(e) => onChange({ ...formData, phone: e.target.value })}
          placeholder="+91-9876543210"
          autoComplete="off"
          className={formErrors.phone ? 'border-red-500' : ''}
        />
        {formErrors.phone && <p className="text-xs text-red-500 mt-1">{formErrors.phone}</p>}
      </div>
      <div>
        <Label htmlFor="email">Email</Label>
        <Input
          id="email"
          type="email"
          value={formData.email}
          onChange={(e) => onChange({ ...formData, email: e.target.value })}
          placeholder="station@example.com"
          autoComplete="off"
          className={formErrors.email ? 'border-red-500' : ''}
        />
        {formErrors.email && <p className="text-xs text-red-500 mt-1">{formErrors.email}</p>}
      </div>
    </div>

    <div>
      <Label htmlFor="gstNumber">GST Number</Label>
      <Input
        id="gstNumber"
        value={formData.gstNumber}
        onChange={(e) => onChange({ ...formData, gstNumber: e.target.value })}
        placeholder="27AABCU9603R1ZX"
        autoComplete="off"
        className={formErrors.gstNumber ? 'border-red-500' : ''}
      />
      {formErrors.gstNumber && <p className="text-xs text-red-500 mt-1">{formErrors.gstNumber}</p>}
    </div>
  </div>
);

// Fuel Prices Section Component

import { useFuelPrices } from '@/hooks/api';

interface FuelPricesSectionProps {
  stationId: string;
}

const FuelPricesSection = ({ stationId }: FuelPricesSectionProps) => {
  const [isExpanded, setIsExpanded] = useState(false);
  const { data: pricesResponse, isLoading } = useFuelPrices(stationId);
  
  // Extract current prices from response
  // Handle both wrapped and unwrapped responses
  let currentPrices: any[] = [];
  if (pricesResponse) {
    if (pricesResponse.data?.current) {
      currentPrices = pricesResponse.data.current;
    } else if (Array.isArray(pricesResponse.data)) {
      currentPrices = pricesResponse.data;
    } else if (pricesResponse.success && pricesResponse.data) {
      currentPrices = pricesResponse.data.current || [];
    }
  }
  
  // Convert to display array
  const fuelPrices = currentPrices
    .filter((p: any) => {
      // Check both 'price' and 'price_per_litre' fields, parse as number if string
      let priceValue = p.price || p.price_per_litre;
      if (typeof priceValue === 'string') priceValue = parseFloat(priceValue);
      return typeof priceValue === 'number' && !isNaN(priceValue) && priceValue > 0;
    })
    .map((p: any) => ({
      fuel_type: p.fuel_type || p.fuelType,
      price_per_litre: typeof p.price === 'string' ? parseFloat(p.price) : (p.price || p.price_per_litre)
    }));

  if (isLoading) {
    return (
      <div className="bg-muted/50 p-3 rounded-lg">
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
          <IndianRupee className="w-4 h-4" />
          <span>Fuel Prices</span>
        </div>
        <div className="text-sm text-muted-foreground">Loading fuel prices...</div>
      </div>
    );
  }

  if (!fuelPrices || fuelPrices.length === 0) {
    return (
      <div className="bg-muted/50 p-3 rounded-lg">
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
          <IndianRupee className="w-4 h-4" />
          <span>Fuel Prices</span>
        </div>
        <div className="text-sm text-muted-foreground">No prices set</div>
      </div>
    );
  }

  return (
    <div className="bg-muted/50 p-3 rounded-lg">
      <button
        onClick={(e) => {
          e.stopPropagation();
          setIsExpanded(!isExpanded);
        }}
        className="flex items-center justify-between w-full text-left md:hidden"
      >
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
          <IndianRupee className="w-4 h-4" />
          <span>Fuel Prices</span>
        </div>
        {isExpanded ? (
          <ChevronUp className="w-4 h-4 text-muted-foreground" />
        ) : (
          <ChevronDown className="w-4 h-4 text-muted-foreground" />
        )}
      </button>
      
      {/* Desktop: Always show */}
      <div className="hidden md:block">
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-3">
          <IndianRupee className="w-4 h-4" />
          <span>Fuel Prices</span>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
          {fuelPrices.map((price: any) => {
            return (
              <div key={price.fuel_type} className="bg-background/50 p-2 rounded border">
                <div className="text-xs text-muted-foreground capitalize">
                  {price.fuel_type}
                </div>
                <div className="text-sm font-semibold text-green-700">
                  ₹{safeToFixed(price.price_per_litre, 2)}
                </div>
              </div>
            );
          })}
        </div>
      </div>
      
      {/* Mobile: Show only when expanded */}
      {isExpanded && (
        <div className="md:hidden">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
            {fuelPrices.map((price: any) => {
              return (
                <div key={price.fuel_type} className="bg-background/50 p-2 rounded border">
                  <div className="text-xs text-muted-foreground capitalize">
                    {price.fuel_type}
                  </div>
                  <div className="text-sm font-semibold text-green-700">
                    ₹{safeToFixed(price.price_per_litre, 2)}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};

export default function StationsManagement() {
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [deleteStationId, setDeleteStationId] = useState<string | null>(null);
  const [formData, setFormData] = useState<StationFormData>(initialFormData);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [editingStation, setEditingStation] = useState<Station | null>(null);

  const { toast } = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  // Fetch stations
  const {
    data: stationsResponse,
    isLoading
  } = useStations();

  const stations = stationsResponse?.success ? stationsResponse.data : [];

  // Update station mutation
  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: StationFormData }) => {
      // Don't send code - it's auto-generated and read-only
      const { code, ...payload } = data;
      const response = await apiClient.put(`/stations/${id}`, payload);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station updated successfully'
      });
      setIsEditDialogOpen(false);
      setEditingStation(null);
      setFormData(initialFormData);
    },
    onError: (error: unknown) => {
      let message = 'Failed to update station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  // Delete station mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiClient.delete(`/stations/${id}`);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station deleted successfully'
      });
      setDeleteStationId(null);
    },
    onError: (error: unknown) => {
      let message = 'Failed to delete station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  // Validation logic
  const validateForm = (data: StationFormData) => {
    const errors: Record<string, string> = {};
    if (!data.name.trim()) {
      errors.name = 'Station name is required';
    } else if (data.name.trim().length < 2) {
      errors.name = 'Station name must be at least 2 characters';
    }
    if (!data.phone.trim()) {
      errors.phone = 'Phone number is required';
    } else if (!/^\d{10}$/.test(data.phone.trim())) {
      errors.phone = 'Enter a valid 10-digit phone number';
    }
    if (data.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email.trim())) {
      errors.email = 'Enter a valid email address';
    }
    if (data.pincode && !/^\d{6}$/.test(data.pincode.trim())) {
      errors.pincode = 'Pincode must be 6 digits';
    }
    if (data.gstNumber) {
      const gst = data.gstNumber.trim().toUpperCase();
      const gstRegex = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/;
      if (!gstRegex.test(gst)) {
        errors.gstNumber = 'Invalid GST number format';
      }
    }
    return errors;
  };

  const isFormValid = Object.keys(validateForm(formData)).length === 0;

  const handleUpdate = () => {
    if (editingStation) {
      updateMutation.mutate({ id: editingStation.id, data: formData });
    }
  };

  const handleEdit = (station: Station) => {
    setEditingStation(station);
    setFormData({
      name: station.name || '',
      code: station.code || '',
      address: station.address || '',
      city: station.city || '',
      state: station.state || '',
      pincode: station.pincode || '',
      phone: station.phone || '',
      email: station.email || '',
      gstNumber: station.gstNumber || ''
    });
    setIsEditDialogOpen(true);
  };

  const handleDelete = () => {
    if (deleteStationId) {
      deleteMutation.mutate(deleteStationId);
    }
  };

  const handleEditDialogOpenChange = (open: boolean) => {
    setIsEditDialogOpen(open);
    if (!open) {
      setEditingStation(null);
      setFormData(initialFormData);
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">Loading stations...</div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 md:p-6 space-y-6 md:space-y-8">
      {/* Header */}
      <div className="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1">
          <h1 className="text-2xl md:text-3xl font-bold tracking-tight">Stations Management</h1>
          <p className="text-muted-foreground text-sm md:text-base">Manage your fuel stations</p>
        </div>
        <Button className="w-full sm:w-auto shadow-sm" onClick={() => navigate('/owner/stations/add')}>
          <Plus className="w-4 h-4 mr-2" />
          Add Station
        </Button>
      </div>

      {/* Stations List */}
      {isLoading ? (
        <Card>
          <CardContent className="py-12">
            <div className="text-center text-muted-foreground">
              Loading stations...
            </div>
          </CardContent>
        </Card>
      ) : Array.isArray(stations) && stations.length > 0 ? (
        <div className="grid gap-4 grid-cols-1">
          {(Array.isArray(stations) ? stations : []).map((station) => {
            return (
            <Card
              key={station.id}
              className="hover:shadow-xl transition-all duration-300 hover:scale-[1.01] cursor-pointer border border-border/50 shadow-md bg-gradient-to-br from-card to-card/80 backdrop-blur-sm overflow-hidden"
              onClick={() => navigate(`/owner/stations/${station.id}`)}
            >
              <CardHeader className="pb-3 bg-gradient-to-r from-primary/5 via-primary/3 to-transparent border-b border-border/30">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3 min-w-0 flex-1">
                    <div className="p-3 rounded-xl bg-gradient-to-br from-primary/20 to-primary/10 flex-shrink-0 ring-1 ring-primary/20">
                      <Building2 className="w-6 h-6 text-primary" />
                    </div>
                    <div className="min-w-0 flex-1 space-y-1">
                      <CardTitle className="text-xl font-bold truncate leading-tight">{station.name}</CardTitle>
                      <div className="flex items-center gap-2 flex-wrap">
                        {station.code && (
                          <Badge variant="outline" className="text-xs font-medium border-primary/30 text-primary">
                            {station.code}
                          </Badge>
                        )}
                        <Badge
                          variant={station.isActive ? 'default' : 'secondary'}
                          className={`text-xs font-medium ${
                            station.isActive
                              ? 'bg-green-100 text-green-800 hover:bg-green-100 border-green-200'
                              : 'bg-gray-100 text-gray-800 hover:bg-gray-100 border-gray-200'
                          }`}
                        >
                          {station.isActive ? '● Active' : '○ Inactive'} ({station.isActive ? 'true' : 'false'})
                        </Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4 p-4" onClick={(e) => e.stopPropagation()}>
                {/* Key Metrics Grid */}
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {/* Today's Sales */}
                  <div className="bg-gradient-to-br from-green-50 to-green-100/50 p-3 rounded-lg border border-green-200/50">
                    <div className="flex items-center gap-2 mb-2">
                      <TrendingUp className="w-4 h-4 text-green-600" />
                      <span className="text-xs font-medium text-green-800">Sales</span>
                    </div>
                    <div className="text-lg font-bold text-green-700">
                      ₹{(station.todaySales || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}
                    </div>
                    <div className="text-xs text-green-600/70">Today</div>
                  </div>

                  {/* Pumps Status */}
                  <div className="bg-gradient-to-br from-blue-50 to-blue-100/50 p-3 rounded-lg border border-blue-200/50">
                    <div className="flex items-center gap-2 mb-2">
                      <Fuel className="w-4 h-4 text-blue-600" />
                      <span className="text-xs font-medium text-blue-800">Pumps</span>
                    </div>
                    <div className="text-lg font-bold text-blue-700">
                      {station.activePumps || 0}/{station.pumpCount || 0}
                    </div>
                    <div className="text-xs text-blue-600/70">Active</div>
                  </div>

                  {/* Last Reading */}
                </div>

                {/* Fuel Prices */}
                <FuelPricesSection stationId={station.id} />

                {/* Location & Contact Info */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {/* Location */}
                  {(station.city || station.address) && (
                    <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/40 border border-border/30">
                      <MapPin className="w-4 h-4 text-muted-foreground mt-0.5 flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <div className="text-xs font-medium text-muted-foreground mb-1">Location</div>
                        <div className="text-sm leading-tight">
                          {station.city && <span>{station.city}</span>}
                          {station.state && <span>{station.city ? `, ${station.state}` : station.state}</span>}
                          {station.address && <div className="text-xs text-muted-foreground mt-1 truncate">{station.address}</div>}
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Contact */}
                  {(station.phone || station.email) && (
                    <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/40 border border-border/30">
                      <Phone className="w-4 h-4 text-muted-foreground mt-0.5 flex-shrink-0" />
                      <div className="flex-1 min-w-0">
                        <div className="text-xs font-medium text-muted-foreground mb-1">Contact</div>
                        <div className="space-y-1">
                          {station.phone && <div className="text-sm truncate">{station.phone}</div>}
                          {station.email && <div className="text-xs text-muted-foreground truncate">{station.email}</div>}
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {/* Plan Info */}
                {station.owner?.plan && (
                  <div className="flex items-center justify-between p-3 rounded-lg bg-gradient-to-r from-orange-50 to-orange-100/50 border border-orange-200/50">
                    <div className="flex items-center gap-2">
                      <div className="w-2 h-2 rounded-full bg-orange-500"></div>
                      <span className="text-sm font-medium text-orange-800">Plan: {station.owner.plan.name}</span>
                    </div>
                    <span className="text-sm font-semibold text-orange-700">
                      ₹{station.owner.plan.priceMonthly}/mo
                    </span>
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex flex-col sm:flex-row gap-2 pt-3 border-t border-border/30">
                  <div className="flex gap-2">
                    <Button
                      size="sm"
                      variant="outline"
                      className="flex-1 sm:flex-none bg-green-50 hover:bg-green-100 border-green-200 text-green-700 hover:text-green-800"
                      onClick={(e) => {
                        e.stopPropagation();
                        navigate(`/owner/daily-settlement/${station.id}`);
                      }}
                    >
                      <TrendingUp className="w-4 h-4 mr-2" />
                      Settle
                    </Button>
                    <Button
                      variant="default"
                      size="sm"
                      className="flex-1 sm:flex-none bg-primary hover:bg-primary/90 text-primary-foreground shadow-sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        navigate(`/owner/stations/${station.id}`);
                      }}
                    >
                      <ArrowRight className="w-4 h-4 mr-2" />
                      Manage
                    </Button>
                  </div>
                  <div className="flex gap-2 sm:ml-auto">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleEdit(station);
                      }}
                      className="hover:bg-blue-50 hover:border-blue-200"
                    >
                      <Edit className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        setDeleteStationId(station.id);
                      }}
                      className="hover:bg-destructive/10 hover:border-destructive/30 text-destructive hover:text-destructive"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
            );
          })}
        </div>
      ) : (
        <Card>
          <CardContent className="py-8 md:py-12">
            <div className="text-center space-y-4">
              <div className="p-4 rounded-full bg-muted/50 w-fit mx-auto">
                <Building2 className="w-12 h-12 md:w-16 md:h-16 text-muted-foreground" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg md:text-xl font-semibold">No Stations Yet</h3>
                <p className="text-muted-foreground text-sm md:text-base max-w-sm mx-auto">
                  Get started by adding your first fuel station
                </p>
                <Button onClick={() => navigate('/owner/stations/add')} className="w-full sm:w-auto mt-4">
                  <Plus className="w-4 h-4 mr-2" />
                  Add Station
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={handleEditDialogOpenChange}>
        <DialogContent className="w-[95vw] max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Station</DialogTitle>
            <DialogDescription>
              Update station information
            </DialogDescription>
          </DialogHeader>
          <StationFormContent formData={formData} onChange={setFormData} />
          <div className="flex flex-col sm:flex-row justify-end gap-2 pt-4">
            <Button variant="outline" onClick={() => handleEditDialogOpenChange(false)} className="w-full sm:w-auto">
              Cancel
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateMutation.isPending || !formData.name}
              className="w-full sm:w-auto"
            >
              {updateMutation.isPending ? 'Updating...' : 'Update Station'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteStationId} onOpenChange={() => setDeleteStationId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Station</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this station? This action cannot be undone.
              All associated data (pumps, nozzles, readings) will also be deleted.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleteMutation.isPending ? 'Deleting...' : 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
