/**
 * Owner Stations Management
 * Complete CRUD for managing stations
 */

import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { 
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { apiClient } from '@/lib/api-client';
import { useStations, queryKeys } from '@/hooks/api';
import { Station } from '@/types/api';
import type { ApiResponse } from '@/lib/api-client';
import { 
  Plus, 
  Building2, 
  Edit, 
  Trash2,
  ArrowRight,
  MapPin,
  Phone,
  Fuel,
  TrendingUp,
  Clock
} from 'lucide-react';

interface StationFormData {
  name: string;
  code: string;
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  email: string;
  gstNumber: string;
}

const initialFormData: StationFormData = {
  name: '',
  code: '',
  address: '',
  city: '',
  state: '',
  pincode: '',
  phone: '',
  email: '',
  gstNumber: ''
};

// Separate component to prevent re-renders
interface StationFormProps {
  formData: StationFormData;
  onChange: (data: StationFormData) => void;
}

const StationFormContent = ({ formData, onChange }: StationFormProps) => (
  <div className="grid gap-4">
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <Label htmlFor="name">Station Name *</Label>
        <Input
          id="name"
          value={formData.name}
          onChange={(e) => onChange({ ...formData, name: e.target.value })}
          placeholder="Main Station"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="code">Station Code</Label>
        <Input
          id="code"
          value={formData.code}
          readOnly
          disabled
          placeholder="Auto-generated by system"
          className="bg-muted cursor-not-allowed"
        />
        <p className="text-xs text-muted-foreground mt-1">Auto-generated by the system</p>
      </div>
    </div>

    <div>
      <Label htmlFor="address">Address</Label>
      <Input
        id="address"
        value={formData.address}
        onChange={(e) => onChange({ ...formData, address: e.target.value })}
        placeholder="Street address"
        autoComplete="off"
      />
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <div>
        <Label htmlFor="city">City</Label>
        <Input
          id="city"
          value={formData.city}
          onChange={(e) => onChange({ ...formData, city: e.target.value })}
          placeholder="Mumbai"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="state">State</Label>
        <Input
          id="state"
          value={formData.state}
          onChange={(e) => onChange({ ...formData, state: e.target.value })}
          placeholder="Maharashtra"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="pincode">Pincode</Label>
        <Input
          id="pincode"
          value={formData.pincode}
          onChange={(e) => onChange({ ...formData, pincode: e.target.value })}
          placeholder="400001"
          autoComplete="off"
        />
      </div>
    </div>

    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div>
        <Label htmlFor="phone">Phone</Label>
        <Input
          id="phone"
          value={formData.phone}
          onChange={(e) => onChange({ ...formData, phone: e.target.value })}
          placeholder="+91-9876543210"
          autoComplete="off"
        />
      </div>
      <div>
        <Label htmlFor="email">Email</Label>
        <Input
          id="email"
          type="email"
          value={formData.email}
          onChange={(e) => onChange({ ...formData, email: e.target.value })}
          placeholder="station@example.com"
          autoComplete="off"
        />
      </div>
    </div>

    <div>
      <Label htmlFor="gstNumber">GST Number</Label>
      <Input
        id="gstNumber"
        value={formData.gstNumber}
        onChange={(e) => onChange({ ...formData, gstNumber: e.target.value })}
        placeholder="27AABCU9603R1ZX"
        autoComplete="off"
      />
    </div>
  </div>
);

export default function StationsManagement() {
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [deleteStationId, setDeleteStationId] = useState<string | null>(null);
  const [formData, setFormData] = useState<StationFormData>(initialFormData);
  const [editingStation, setEditingStation] = useState<Station | null>(null);

  const { toast } = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  // Fetch stations
  const {
    data: stationsResponse,
    isLoading
  } = useStations() as { data?: ApiResponse<Station[]> | undefined; isLoading: boolean };

  const stations = stationsResponse?.data ?? [];

  // Create station mutation
  const createMutation = useMutation({
    mutationFn: async (data: StationFormData) => {
      // Don't send code - backend generates it
      const { code, ...payload } = data;
      const response = await apiClient.post('/stations', payload);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station created successfully'
      });
      setIsAddDialogOpen(false);
      setFormData(initialFormData);
    },
    onError: (error: unknown) => {
      let message = 'Failed to create station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  // Update station mutation
  const updateMutation = useMutation({
    mutationFn: async ({ id, data }: { id: string; data: StationFormData }) => {
      // Don't send code - it's auto-generated and read-only
      const { code, ...payload } = data;
      const response = await apiClient.put(`/stations/${id}`, payload);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station updated successfully'
      });
      setIsEditDialogOpen(false);
      setEditingStation(null);
      setFormData(initialFormData);
    },
    onError: (error: unknown) => {
      let message = 'Failed to update station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  // Delete station mutation
  const deleteMutation = useMutation({
    mutationFn: async (id: string) => {
      const response = await apiClient.delete(`/stations/${id}`);
      return response;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.stations });
      toast({
        title: 'Success',
        description: 'Station deleted successfully'
      });
      setDeleteStationId(null);
    },
    onError: (error: unknown) => {
      let message = 'Failed to delete station';
      if (error && typeof error === 'object') {
        const errObj = error as { response?: { data?: { error?: string } } };
        if (
          errObj.response &&
          typeof errObj.response === 'object' &&
          errObj.response.data &&
          typeof errObj.response.data === 'object' &&
          'error' in errObj.response.data
        ) {
          message = errObj.response.data.error || message;
        }
      }
      toast({
        title: 'Error',
        description: message,
        variant: 'destructive'
      });
    }
  });

  const handleCreate = () => {
    createMutation.mutate(formData);
  };

  const handleUpdate = () => {
    if (editingStation) {
      updateMutation.mutate({ id: editingStation.id, data: formData });
    }
  };

  const handleEdit = (station: Station) => {
    setEditingStation(station);
    setFormData({
      name: station.name || '',
      code: station.code || '',
      address: station.address || '',
      city: station.city || '',
      state: station.state || '',
      pincode: station.pincode || '',
      phone: station.phone || '',
      email: station.email || '',
      gstNumber: station.gstNumber || ''
    });
    setIsEditDialogOpen(true);
  };

  const handleDelete = () => {
    if (deleteStationId) {
      deleteMutation.mutate(deleteStationId);
    }
  };

  const handleAddDialogOpenChange = (open: boolean) => {
    setIsAddDialogOpen(open);
    if (!open) {
      setFormData(initialFormData);
    }
  };

  const handleEditDialogOpenChange = (open: boolean) => {
    setIsEditDialogOpen(open);
    if (!open) {
      setEditingStation(null);
      setFormData(initialFormData);
    }
  };

  // Loading state
  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">Loading stations...</div>
      </div>
    );
  }

  return (
    <div className="container mx-auto p-4 md:p-6 space-y-6 md:space-y-8">
      {/* Header */}
      <div className="flex flex-col space-y-4 sm:space-y-0 sm:flex-row sm:items-center sm:justify-between">
        <div className="space-y-1">
          <h1 className="text-2xl md:text-3xl font-bold tracking-tight">Stations Management</h1>
          <p className="text-muted-foreground text-sm md:text-base">Manage your fuel stations</p>
        </div>
        <Dialog open={isAddDialogOpen} onOpenChange={handleAddDialogOpenChange}>
          <DialogTrigger asChild>
            <Button className="w-full sm:w-auto shadow-sm">
              <Plus className="w-4 h-4 mr-2" />
              Add Station
            </Button>
          </DialogTrigger>
          <DialogContent className="w-[95vw] max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Add New Station</DialogTitle>
              <DialogDescription>
                Create a new fuel station
              </DialogDescription>
            </DialogHeader>
            <StationFormContent formData={formData} onChange={setFormData} />
            <div className="flex flex-col sm:flex-row justify-end gap-2 pt-4">
              <Button variant="outline" onClick={() => handleAddDialogOpenChange(false)} className="w-full sm:w-auto">
                Cancel
              </Button>
              <Button
                onClick={handleCreate}
                disabled={createMutation.isPending || !formData.name}
                className="w-full sm:w-auto"
              >
                {createMutation.isPending ? 'Creating...' : 'Create Station'}
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Stations List */}
      {isLoading ? (
        <Card>
          <CardContent className="py-12">
            <div className="text-center text-muted-foreground">
              Loading stations...
            </div>
          </CardContent>
        </Card>
      ) : Array.isArray(stations) && stations.length > 0 ? (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {(Array.isArray(stations) ? stations : []).map((station) => (
            <Card
              key={station.id}
              className="hover:shadow-lg transition-all duration-200 hover:scale-[1.02] cursor-pointer border-0 shadow-sm bg-card/50 backdrop-blur-sm"
              onClick={() => navigate(`/owner/stations/${station.id}`)}
            >
              <CardHeader className="pb-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-3 min-w-0 flex-1">
                    <div className="p-2 rounded-lg bg-primary/10 flex-shrink-0">
                      <Building2 className="w-5 h-5 text-primary" />
                    </div>
                    <div className="min-w-0 flex-1">
                      <CardTitle className="text-lg font-semibold truncate">{station.name}</CardTitle>
                      {station.code && (
                        <CardDescription className="text-sm">Code: {station.code}</CardDescription>
                      )}
                    </div>
                  </div>
                  <Badge
                    variant={station.isActive ? 'default' : 'secondary'}
                    className={`flex-shrink-0 text-xs font-medium ${
                      station.isActive
                        ? 'bg-green-100 text-green-800 hover:bg-green-100'
                        : 'bg-gray-100 text-gray-800 hover:bg-gray-100'
                    }`}
                  >
                    {station.isActive ? 'Active' : 'Inactive'}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-4" onClick={(e) => e.stopPropagation()}>
                {/* Today's Sales - Prominent */}
                {station.todaySales !== undefined && station.todaySales !== null && (
                  <div className="bg-gradient-to-r from-green-50 to-transparent p-4 rounded-lg border border-green-200">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-2">
                        <TrendingUp className="w-4 h-4 text-green-600" />
                        <span className="text-sm font-medium text-green-800">Today's Sales</span>
                      </div>
                      <span className="text-xl font-bold text-green-700">
                        ₹{station.todaySales.toLocaleString('en-IN', { maximumFractionDigits: 0 })}
                      </span>
                    </div>
                  </div>
                )}

                {/* Stats Grid */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="bg-muted/50 p-3 rounded-lg">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
                      <Fuel className="w-4 h-4" />
                      <span>Pumps</span>
                    </div>
                    <div className="font-semibold text-lg">
                      {station.activePumps}/{station.pumpCount}
                      <span className="text-xs text-muted-foreground ml-1 block">active</span>
                    </div>
                  </div>

                  {station.lastReading && (
                    <div className="bg-muted/50 p-3 rounded-lg">
                      <div className="flex items-center gap-2 text-sm text-muted-foreground mb-2">
                        <Clock className="w-4 h-4" />
                        <span>Last Entry</span>
                      </div>
                      <div className="text-sm font-medium">
                        {new Date(station.lastReading).toLocaleDateString('en-IN', {
                          month: 'short',
                          day: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit'
                        })}
                      </div>
                    </div>
                  )}
                </div>

                {/* Location */}
                {(station.city || station.address) && (
                  <div className="flex items-start gap-3 p-3 rounded-lg bg-muted/30">
                    <MapPin className="w-4 h-4 text-muted-foreground mt-0.5 flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <span className="text-sm text-muted-foreground leading-relaxed">
                        {station.city && <span>{station.city}{station.state && `, ${station.state}`}</span>}
                      </span>
                    </div>
                  </div>
                )}

                {/* Contact */}
                {station.phone && (
                  <div className="flex items-center gap-3 p-3 rounded-lg bg-muted/30">
                    <Phone className="w-4 h-4 text-muted-foreground flex-shrink-0" />
                    <span className="text-sm text-muted-foreground">{station.phone}</span>
                  </div>
                )}

                {/* Actions */}
                <div className="space-y-2 pt-3 border-t">
                  <div className="flex gap-2">
                    <Button
                      variant="default"
                      size="sm"
                      className="flex-1 hover:bg-primary/90"
                      onClick={(e) => {
                        e.stopPropagation();
                        navigate(`/owner/stations/${station.id}`);
                      }}
                    >
                      <ArrowRight className="w-4 h-4 mr-2" />
                      Manage
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleEdit(station);
                      }}
                      className="hover:bg-primary/5"
                    >
                      <Edit className="w-4 h-4" />
                    </Button>
                    <Button
                      variant="destructive"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        setDeleteStationId(station.id);
                      }}
                      className="hover:bg-destructive/90"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                  <Button
                    variant="secondary"
                    size="sm"
                    className="w-full hover:bg-secondary/80"
                    onClick={(e) => {
                      e.stopPropagation();
                      navigate(`/owner/daily-settlement/${station.id}`);
                    }}
                  >
                    Daily Settlement
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      ) : (
        <Card>
          <CardContent className="py-8 md:py-12">
            <div className="text-center space-y-4">
              <div className="p-4 rounded-full bg-muted/50 w-fit mx-auto">
                <Building2 className="w-12 h-12 md:w-16 md:h-16 text-muted-foreground" />
              </div>
              <div className="space-y-2">
                <h3 className="text-lg md:text-xl font-semibold">No Stations Yet</h3>
                <p className="text-muted-foreground text-sm md:text-base max-w-sm mx-auto">
                  Get started by adding your first fuel station
                </p>
                <Button onClick={() => setIsAddDialogOpen(true)} className="w-full sm:w-auto mt-4">
                  <Plus className="w-4 h-4 mr-2" />
                  Add Station
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={handleEditDialogOpenChange}>
        <DialogContent className="w-[95vw] max-w-2xl mx-4 max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Station</DialogTitle>
            <DialogDescription>
              Update station information
            </DialogDescription>
          </DialogHeader>
          <StationFormContent formData={formData} onChange={setFormData} />
          <div className="flex flex-col sm:flex-row justify-end gap-2 pt-4">
            <Button variant="outline" onClick={() => handleEditDialogOpenChange(false)} className="w-full sm:w-auto">
              Cancel
            </Button>
            <Button
              onClick={handleUpdate}
              disabled={updateMutation.isPending || !formData.name}
              className="w-full sm:w-auto"
            >
              {updateMutation.isPending ? 'Updating...' : 'Update Station'}
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation */}
      <AlertDialog open={!!deleteStationId} onOpenChange={() => setDeleteStationId(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Station</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete this station? This action cannot be undone.
              All associated data (pumps, nozzles, readings) will also be deleted.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDelete}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {deleteMutation.isPending ? 'Deleting...' : 'Delete'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
